# Debug configuration for Otsu Obliterator
debug:
  # Core debug features
  logging:
    enabled: true
    level: "info"  # debug, info, warning, error
    format: "text"  # text, json
    output: "stdout"  # stdout, stderr, file
    
  memory_tracking:
    enabled: true
    stack_traces: false
    leak_detection: true
    pool_monitoring: true
    
  file_tracking:
    enabled: true
    leak_detection: true
    track_all_operations: false
    
  timing_tracking:
    enabled: true
    detailed_operations: false
    
  # Event system
  event_bus:
    buffer_size: 1000
    max_subscribers: 50
    
# Environment-specific configurations
environments:
  development:
    debug:
      logging:
        level: "debug"
        stack_traces: true
      memory_tracking:
        stack_traces: true
        detailed_operations: true
      timing_tracking:
        detailed_operations: true
        
  production:
    debug:
      logging:
        level: "error"
        format: "json"
      memory_tracking:
        enabled: false
      file_tracking:
        enabled: false
      timing_tracking:
        enabled: false
        
  testing:
    debug:
      logging:
        level: "warning"
        output: "stderr"
      memory_tracking:
        stack_traces: true
      event_bus:
        buffer_size: 100
